### ISSUE TITLE
Refactor functions for better design

### ISSUE THREAD

**Issue by kelly-sovacool** [SchlossLab/mikRopML#114]
**Functions**:
- [x] compute_corr_mat https://github.com/SchlossLab/mikRopML/issues/109
- [x] get_tuning_grid https://github.com/SchlossLab/mikRopML/issues/110
- [x] calc_aucs https://github.com/SchlossLab/mikRopML/issues/111
- [x] get_feature_importance https://github.com/SchlossLab/mikRopML/issues/112
- [x] run_pipeline https://github.com/SchlossLab/mikRopML/issues/113

**Things to address** while editing all of the above functions:
- names should follow tidyverse style guide https://github.com/SchlossLab/mikRopML/issues/95
- all function inputs/outputs should be R objects; no files written to disk https://github.com/SchlossLab/mikRopML/issues/96
- unit tests https://github.com/SchlossLab/mikRopML/issues/97
- input validation https://github.com/SchlossLab/mikRopML/issues/98
- update Roxygen comments https://github.com/SchlossLab/mikRopML/issues/58
- when changing a function's name, inputs, or outputs, also fix the code that calls that function.

**Notes**:
- Run `devtools::check()` before pushing commits so you know your code works.
