### ISSUE TITLE
Go through JOSS checklist

### ISSUE THREAD

**Issue by pschloss** [SchlossLab/mikropml#169]
### General checks

- [x] Repository: Is the source code for this software available at the repository url?
- [x] License: Does the repository contain a plain-text LICENSE file with the contents of an OSI approved software license? **I think the names listed in the copyright should match the co-author list**
- [X] Contribution and authorship: Has the submitting author made major contributions to the software? Does the full list of paper authors seem appropriate and complete? **(@kelly-sovacool will submit)**
- [X] Substantial scholarly effort: Does this submission meet the scope eligibility described in the JOSS guidelines

### Functionality

- [X] Installation: Does installation proceed as outlined in the documentation?
- [X] Functionality: Have the functional claims of the software been confirmed? **We thoroughly test all package functionality with testthat and report our [code coverage with covr](https://codecov.io/gh/SchlossLab/mikropml).**
- [X] Performance: If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [X] A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] Installation instructions: Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution. **These are handled by the installation, but I think it would be a good idea to provide a list of the packages that are used in the README.**
- [X] Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [X] Functionality documentation: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [X] Automated tests: Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support. **See https://github.com/SchlossLab/mikRopML/blob/master/.github/CONTRIBUTING.md**

### Software paper
- [X] Summary: Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] State of the field: Do the authors describe how this software compares to other commonly-used packages?
- [x] Quality of writing: Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [X] References: Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper citation syntax?

**Comment by pschloss** [comment]
Should `CONTRIBUTING.md` be in the repository's root directory? I'm not sure how someone coming to the repo would see it stashed away in `.github/`

**Comment by kelly-sovacool** [comment]
> Should `CONTRIBUTING.md` be in the repository's root directory? I'm not sure how someone coming to the repo would see it stashed away in `.github/`. Maybe there could be a link in `README`?

It's standard practice to be in `.github/`. I also added a link to it in the `README` (not yet merged).

**Comment by kelly-sovacool** [comment]
Closing this because we double-checked this prior to submitting to JOSS and the review is underway
